name: phone_number
description: Flutter plugin for parsing, formatting and validating international phone numbers.
version: 1.0.0-dev.1
homepage: https://github.com/nashfive/phone_number

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.julienvignali.phone_number
        pluginClass: PhoneNumberPlugin
      ios:
        pluginClass: PhoneNumberPlugin
